name: Code Quality
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Turbo Linting
        run: pnpm lint
      - name: Qodana Analysis
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Super Analysis
        uses: super-linter/super-linter@v6.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}