name: Code Quality
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

jobs:

  qodana:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup-environment.yml
    steps:
      - name: Qodana Analysis
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  turbo:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup-environment.yml
    steps:
      - name: Turbo Linting
        run: pnpm lint

#  super:
#    needs: [setup]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Super Analysis
#        uses: super-linter/super-linter@v6.5.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}